# Generated by Django 5.0.4 on 2024-06-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_decorations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorations',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
