# Generated by Django 5.0.4 on 2024-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_decorations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorations',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
