# Generated by Django 5.0.4 on 2024-05-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0021_remove_feedback_program_id_and_more'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registevevnts',
            name='evnt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e', to='Auth_app.events'),
        ),
    ]
