# Generated by Django 5.0.4 on 2024-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_registevevnts_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registevevnts',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
