# Generated by Django 5.0.4 on 2024-05-27 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_alter_registevevnts_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(default='', max_length=500)),
                ('member2', models.CharField(default='', max_length=500)),
                ('member3', models.CharField(default='', max_length=500)),
                ('member4', models.CharField(default='', max_length=500)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
