# Generated by Django 5.0.4 on 2024-05-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member1',
        ),
    ]
