# Generated by Django 5.0.4 on 2024-05-29 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0029_alter_events_status'),
        ('participants', '0009_remove_group_member1'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='evnt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esdfsd', to='Auth_app.events'),
        ),
    ]
