# Generated by Django 5.0.3 on 2024-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='firm_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
