# Generated by Django 5.0.3 on 2024-03-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0003_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='ptime',
            field=models.TimeField(null=True),
        ),
    ]
