# Generated by Django 5.0.3 on 2024-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('Feedback_msg', models.CharField(max_length=100)),
            ],
        ),
    ]
