# Generated by Django 5.0.3 on 2024-03-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0010_category_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='category',
        ),
    ]
