# Generated by Django 5.0.3 on 2024-03-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0012_programs_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
