# Generated by Django 5.0.3 on 2024-04-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0013_programs_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='register',
            name='pin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
