# Generated by Django 5.0.3 on 2024-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0015_register_admissionnum_register_collegename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='idproof',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
