# Generated by Django 5.0.4 on 2024-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0016_alter_register_idproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cource',
            field=models.CharField(choices=[('', 'Select'), ('Bsc cs', 'Bsc cs'), ('BCA', 'BCA')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
