# Generated by Django 5.0.4 on 2024-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0017_alter_register_cource_alter_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='event_id',
        ),
        migrations.AddField(
            model_name='events',
            name='stime',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='programs',
        ),
    ]
