# Generated by Django 5.0.4 on 2024-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0018_remove_programs_category_id_remove_programs_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='TotalCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='etime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='rules',
            field=models.TextField(default=''),
        ),
    ]
