# Generated by Django 5.0.4 on 2024-05-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0019_events_fees_events_totalcost_events_etime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='etime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='stime',
            field=models.TimeField(null=True),
        ),
    ]
