# Generated by Django 5.0.4 on 2024-05-21 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0020_alter_events_etime_alter_events_stime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='program_id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_msg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL),
        ),
    ]
