# Generated by Django 5.0.4 on 2024-05-22 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0021_remove_feedback_program_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t', to=settings.AUTH_USER_MODEL),
        ),
    ]
