# Generated by Django 5.0.4 on 2024-05-22 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0022_events_first_events_second_events_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sponserid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponserid', to=settings.AUTH_USER_MODEL),
        ),
    ]
