# Generated by Django 5.0.4 on 2024-05-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0023_events_sponserid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='edate',
        ),
    ]
