# Generated by Django 5.0.4 on 2024-05-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0024_remove_events_edate'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register',
            name='department',
            field=models.CharField(choices=[('', 'Select'), ('', ''), ('', '')], default='', max_length=50),
        ),
    ]
