# Generated by Django 5.0.4 on 2024-05-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0025_events_cod_alter_register_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cource',
            field=models.CharField(choices=[('', 'Select'), ('Bsc cs', 'Bsc cs'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MSC CS', 'MSC CS'), ('other', 'other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
