# Generated by Django 5.0.4 on 2024-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0026_alter_register_cource_alter_register_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('', 'Select'), ('single', 'single'), ('group', 'group')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='register',
            name='cource',
            field=models.CharField(default='', max_length=50),
        ),
    ]
