# Generated by Django 5.0.6 on 2024-05-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0027_events_event_type_alter_register_cource'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
