# Generated by Django 5.0.6 on 2024-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0028_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
