# Generated by Django 5.0.4 on 2024-06-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0030_events_spostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='realname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
