# Generated by Django 5.0.4 on 2024-05-22 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_app', '0023_events_sponserid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sponserevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ImageField(blank=True, null=True, upload_to='')),
                ('evnt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esid', to='Auth_app.events')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
