# Generated by Django 5.0.4 on 2024-06-08 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_decorations'),
        ('sponser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sponserdecorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edecsid', to='Admin_app.decorations')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdecid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
