# Generated by Django 5.0.2 on 2024-06-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponser', '0002_sponserdecorations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponserdecorations',
            name='adphoto',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
