# Generated by Django 5.0.4 on 2024-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponser', '0003_sponserdecorations_adphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponserdecorations',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
